### ISSUE TITLE
Problemas con Chalk

### ISSUE THREAD

**Issue by JoelFEscobar** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct11-async-sockets-alu0101130408#1]
Buenas tardes @esegredo.
He estado intentando implementar la función encargada de leer una nota dada en el cliente. para ello, encontre en el siguiente [recurso](https://stackoverflow.com/questions/58389081/typescript-error-when-dynamically-setting-color-for-chalk-package) el uso de una opcion de chalk llamada 'keyword' que permite especificar un color para un texto dato siendo el uso de este `chalk.keyword(color)(text)` He intentado utilizarlo para visualizar dado el color de la nota y mostrar su contendio por consola con ese color. Sin embargo, al probar su funcionamiento me salta el siguiente error:

```
                console.log(chalk.keyword(noteObject.color)('Title:' + noteObject.title));
                                  ^

TypeError: chalk.keyword is not a function
    at MessageEventEmitterClient.<anonymous> (/home/usuario/ull-esit-inf-dsi-21-22-prct11-async-sockets-alu0101130408/dist/client/client.js:58:35)
    at MessageEventEmitterClient.emit (node:events:526:28)
    at Socket.<anonymous> (/home/usuario/ull-esit-inf-dsi-21-22-prct11-async-sockets-alu0101130408/dist/client/event.js:15:22)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v17.5.0

```

En el cual interpreto que es que no reconoce el uso de este comando, no se si puede ser debido a que he de instalar algun paquete o version o como solucionar este error, puesto que no encuentro ninguna solucion.

Un saludo y gracias de antemano, Joel.

**Comment by esegredo** [comment]
Hola, buenas tardes.

Intenta buscar una solución alternativa. Ya hay gente que me ha indicado que ha tenido problemas con `keyword`. Podría darse el caso, también, de que la versión de `chalk` que estás utilizando no incorpore dicho método.

Saludos.
